### ISSUE TITLE
question: weird error while installing gorocksdb

### ISSUE THREAD

**Issue by olcayseker** [drausin/libri#241]
I am trying to build and debug this project just for curiosity. I am having trouble to setup gorocksdb. Running install-gorocksdb.sh gives those;

 github.com/tecbot/gorocksdb
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:43:17: could not determine kind of name for C.rocksdb_approximate_memory_usage_create
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:49:8: could not determine kind of name for C.rocksdb_approximate_memory_usage_destroy
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:55:32: could not determine kind of name for C.rocksdb_approximate_memory_usage_get_cache_total
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:54:32: could not determine kind of name for C.rocksdb_approximate_memory_usage_get_mem_table_readers_total
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:52:32: could not determine kind of name for C.rocksdb_approximate_memory_usage_get_mem_table_total
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:53:32: could not determine kind of name for C.rocksdb_approximate_memory_usage_get_mem_table_unflushed
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:37:4: could not determine kind of name for C.rocksdb_memory_consumers_add_cache
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:32:4: could not determine kind of name for C.rocksdb_memory_consumers_add_db
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:27:15: could not determine kind of name for C.rocksdb_memory_consumers_create
../go/src/github.com/tecbot/gorocksdb/memory_usage.go:28:8: could not determine kind of name for C.rocksdb_memory_consumers_destroy

Any recommendations about what i am missing?

**Comment by drausin** [comment]
hey @olcayseker, my guess is that the gorocksdb version you're using isn't compatible with the RocksDB version

Are you using RocksDB v5.15.10 (the default in `install-rocksdb.sh`)? If so, looks like [gorocksdb requires v5.16.+](https://github.com/tecbot/gorocksdb)

An alternative would be to run things from within the build container, which already has the proper RocksDB and gorocksdb versions pre-installed:
```
./scripts/run-build-container.sh
```

**Comment by olcayseker** [comment]
Hi @drausin, thanks for your interest. 
I am not sure if it makes difference but i think i need to mention my dev environment.
Ubuntu 18.04 with latest updates with go version go1.11.4 linux/amd64 and VSCode.
What i have done so far is;
1-installed rocksdb dependencies which is explained here https://github.com/facebook/rocksdb/blob/master/INSTALL.md
2-Change install-rocksdb.sh line 5 to ROCKSDB_VERSION='5.17.2'
3-Change install-gorocksdb.sh line 11 to CGO_LDFLAGS="-L/usr/local/lib/librocksdb.a -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd"
I am not sure if i need to open a PR but alas. After all i started to see below

com/libri/libri>Finished running tool: /usr/local/go/bin/go build -i -o /tmp/vscode-gowF4MXW/go-code-check github.com/libri/libri
/tmp/rocksdb/util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/tmp/rocksdb/util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/tmp/rocksdb/util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/tmp/rocksdb/util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/tmp/rocksdb/util/compression.h:95: undefined reference to `ZSTD_freeDCtx'  ..... etc

Obviously this is a dependency problem but annoying.
![image](https://user-images.githubusercontent.com/776387/50386189-250ded00-06f3-11e9-9b97-788e6e0d4fa6.png)
